# Generated by Django 3.0.7 on 2020-06-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='short_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=20, null=True)),
                ('long_url', models.URLField(max_length=512, unique=True, verbose_name='URL')),
            ],
        ),
    ]
