# Generated by Django 3.0.7 on 2020-06-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_urls',
            name='slug',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='short_urls',
            name='short_url',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
