# Generated by Django 3.0.7 on 2020-06-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200629_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_urls',
            name='slug',
        ),
    ]
