# Generated by Django 3.0.7 on 2020-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_short_urls_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_urls',
            name='long_url',
            field=models.URLField(max_length=512, unique=True, verbose_name='URL'),
        ),
    ]
