# Generated by Django 3.0.7 on 2020-08-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='user',
        ),
    ]
