# Generated by Django 3.0.7 on 2020-08-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200830_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='occupation_sector',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
