# Generated by Django 3.0.7 on 2020-09-01 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_userprofile_occupation_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_created_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=20, null=True)),
                ('long_url', models.URLField(max_length=512, verbose_name='URL')),
                ('slug', models.CharField(max_length=16, null=True)),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
