# Generated by Django 3.0.7 on 2020-09-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200901_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_urls',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='short_urls',
            name='user',
        ),
    ]
