# Generated by Django 3.0.7 on 2020-09-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200904_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_created_url',
            old_name='long_url_auth',
            new_name='long_url',
        ),
    ]
