# Generated by Django 3.0.7 on 2020-09-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200904_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_created_url',
            old_name='long_url_authenticated',
            new_name='long_url',
        ),
    ]
