# Generated by Django 3.0.7 on 2020-09-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200904_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='short_urls',
        ),
    ]
