# Generated by Django 3.0.7 on 2020-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_short_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='short_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=20, null=True)),
                ('long_url', models.URLField(max_length=512, verbose_name='URL')),
                ('slug', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
