# Generated by Django 3.0.7 on 2020-09-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_short_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_urls',
            name='slug',
        ),
    ]
